name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  install-lint-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: |
          set -o pipefail 
          pnpm install --frozen-lockfile

      - name: Run Prettier check
        run: |
          set -o pipefail 
          pnpm format:check

      - name: Run ESLint check
        run: |
          set -o pipefail 
          pnpm lint

      # - name: Analyze unused files and dependencies
      #   run: pnpm knip

      - name: Build the project
        run: |
          set -o pipefail 
          pnpm build
